# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# vim: set filetype=python:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{5e7a12d4-fd22-43fb-894f-9a9da5cf8fda}',
        'contract_ids': ['@astian.org/midori-blocker-engine;1'],
        'legacy_constructor': 'midori_blocker_xpcom_constructor',
        'headers': ['/browser/components/blocker/MidoriBlockerXPCOM.h'],
    },
    {
        'cid': '{d4ca9908-c83d-4bc4-872d-84342d2ed964}',
        'contract_ids': ['@astian.org/midori-blocker-content-policy;1'],
        'type': 'MidoriBlockerContentPolicy',
        'headers': ['/browser/components/blocker/MidoriBlockerXPCOM.h'],
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
        'categories': {'content-policy': '@astian.org/midori-blocker-content-policy;1'},
    },
    {
        'cid': '{0e2e9983-bee8-4d1e-a74f-3b8265ea96ba}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=contentblocked'],
        'esModule': 'resource:///modules/MidoriBlockedPage.sys.mjs',
        'constructor': 'MidoriBlockedPage',
    },
]
