# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{57bf4bce-8d3b-4a85-8740-1cc83363409d}",
        "contract_ids": ["@astian.org/midori-sync-crypto;1"],
        "type": "MidoriSyncCrypto",
        "headers": ["/toolkit/components/midori-sync/MidoriSyncCrypto.h"],
        "init_method": "Init",
        "processes": ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
