#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# download-addons.sh — Downloads and integrates addons from amelia.json
# into engine/browser/extensions/ as builtin-addons for the Mozilla build system.
#
# Usage: bash scripts/download-addons.sh [--force]
#   --force: Re-download and overwrite even if addon files already exist

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AMELIA_JSON="$PROJECT_DIR/amelia.json"
ENGINE_DIR="$PROJECT_DIR/engine"
EXTENSIONS_DIR="$ENGINE_DIR/browser/extensions"
TMP_DIR="$PROJECT_DIR/.tmp-addons"

create_stub_manifest() {
        local addon_dir="$1"
        local addon_key="$2"
        local addon_id="$3"

        mkdir -p "$addon_dir"
        cat > "$addon_dir/manifest.json" <<EOF
{
    "manifest_version": 2,
    "name": "$addon_key (stub)",
    "version": "0.0.0",
    "description": "Fallback stub generated by build system when addon download/integration fails.",
    "browser_specific_settings": {
        "gecko": {
            "id": "$addon_id"
        }
    }
}
EOF
}

flatten_single_root_if_needed() {
        local addon_dir="$1"
        local extracted_root

        if [[ -f "$addon_dir/manifest.json" ]]; then
                return
        fi

        extracted_root=$(find "$addon_dir" -mindepth 1 -maxdepth 1 -type d | head -1)
        if [[ -n "$extracted_root" ]] && [[ -f "$extracted_root/manifest.json" ]]; then
                if [[ $(find "$addon_dir" -mindepth 1 -maxdepth 1 -type d | wc -l) -eq 1 ]] && [[ $(find "$addon_dir" -mindepth 1 -maxdepth 1 -type f | wc -l) -eq 0 ]]; then
                        find "$extracted_root" -mindepth 1 -maxdepth 1 -exec mv {} "$addon_dir/" \;
                        rmdir "$extracted_root"
                        echo "INFO: Flattened nested archive root for $(basename "$addon_dir")"
                fi
        fi
}

sync_file_to_src() {
    local src_file="$1"
    local dst_file="$2"

    mkdir -p "$(dirname "$dst_file")"

    if [[ -e "$dst_file" ]]; then
        local src_real
        local dst_real
        src_real="$(readlink -f "$src_file")"
        dst_real="$(readlink -f "$dst_file")"
        if [[ "$src_real" == "$dst_real" ]]; then
            echo "INFO: Source and destination are the same file, skipping sync: $dst_file"
            return 0
        fi
    fi

    cp "$src_file" "$dst_file"
}

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
    FORCE=true
fi

# Check dependencies
for cmd in jq curl unzip; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' is required but not found. Please install it."
        exit 1
    fi
done

if [[ ! -f "$AMELIA_JSON" ]]; then
    echo "ERROR: amelia.json not found at $AMELIA_JSON"
    exit 1
fi

if [[ ! -d "$ENGINE_DIR" ]]; then
    echo "ERROR: engine/ directory not found. Run 'amelia download' first."
    exit 1
fi

# Read addons from amelia.json
ADDON_KEYS=$(jq -r '.addons // {} | keys[]' "$AMELIA_JSON" 2>/dev/null)
if [[ -z "$ADDON_KEYS" ]]; then
    echo "INFO: No addons defined in amelia.json"
    exit 0
fi

mkdir -p "$TMP_DIR"

# Track which addons we process for moz.build registration
PROCESSED_ADDONS=()

for ADDON_KEY in $ADDON_KEYS; do
    echo ""
    echo "=== Processing addon: $ADDON_KEY ==="

    # Read addon config
    ADDON_ID=$(jq -r ".addons[\"$ADDON_KEY\"].id" "$AMELIA_JSON")
    PLATFORM=$(jq -r ".addons[\"$ADDON_KEY\"].platform // \"unknown\"" "$AMELIA_JSON")
    ADDON_DIR="$EXTENSIONS_DIR/$ADDON_KEY"

    # Check if addon already has files (not just empty dir)
    FILE_COUNT=0
    if [[ -d "$ADDON_DIR" ]]; then
        FILE_COUNT=$(find "$ADDON_DIR" -type f ! -name "moz.build" ! -name "jar.mn" | wc -l)
    fi

    if [[ "$FILE_COUNT" -gt 0 ]] && [[ "$FORCE" != "true" ]]; then
        echo "INFO: $ADDON_KEY already has $FILE_COUNT files. Skipping download (use --force to re-download)."
    else
        # Resolve download URL based on platform
        DOWNLOAD_URL=""
        case "$PLATFORM" in
            url)
                DOWNLOAD_URL=$(jq -r ".addons[\"$ADDON_KEY\"].url" "$AMELIA_JSON")
                ;;
            github)
                REPO=$(jq -r ".addons[\"$ADDON_KEY\"].repo" "$AMELIA_JSON")
                VERSION=$(jq -r ".addons[\"$ADDON_KEY\"].version" "$AMELIA_JSON")
                FILE_GLOB=$(jq -r ".addons[\"$ADDON_KEY\"].fileGlob" "$AMELIA_JSON")

                echo "INFO: Fetching release info from GitHub: $REPO @ $VERSION"
                RELEASE_JSON=$(curl -sL \
                    -H "User-Agent: midori-build-addon-downloader" \
                    "https://api.github.com/repos/$REPO/releases/tags/$VERSION")

                # Prefer exact asset match. If release names change, fallback to latest Firefox zip.
                DOWNLOAD_URL=$(echo "$RELEASE_JSON" | jq -r \
                    --arg glob "$FILE_GLOB" \
                    '([.assets[]? | select(.name == $glob)] | .[0].browser_download_url) // empty' 2>/dev/null)

                if [[ -z "$DOWNLOAD_URL" ]]; then
                    DOWNLOAD_URL=$(echo "$RELEASE_JSON" | jq -r \
                        '([.assets[]? | select((.name | ascii_downcase | contains("firefox")) and (.name | endswith(".zip")))] | sort_by(.updated_at) | reverse | .[0].browser_download_url) // empty' 2>/dev/null)
                    if [[ -n "$DOWNLOAD_URL" ]]; then
                        echo "WARNING: Exact asset '$FILE_GLOB' not found, using latest Firefox zip fallback"
                    fi
                fi

                if [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]]; then
                    echo "WARNING: Could not find asset matching '$FILE_GLOB' in $REPO @ $VERSION"
                    echo "WARNING: Available assets:"
                    echo "$RELEASE_JSON" | jq -r '.assets[].name' 2>/dev/null || echo "  (none)"
                    echo "WARNING: Creating stub addon for $ADDON_KEY so build can continue"

                    rm -rf "$ADDON_DIR"
                    create_stub_manifest "$ADDON_DIR" "$ADDON_KEY" "$ADDON_ID"
                fi
                ;;
            amo)
                AMO_ID=$(jq -r ".addons[\"$ADDON_KEY\"].amoId" "$AMELIA_JSON")
                echo "INFO: Fetching from AMO: $AMO_ID"
                DOWNLOAD_URL=$(curl -sL "https://addons.mozilla.org/api/v4/addons/addon/$AMO_ID/versions/" | \
                    jq -r '.results[0].files[0].url' 2>/dev/null)
                ;;
            *)
                echo "ERROR: Unknown platform '$PLATFORM' for addon $ADDON_KEY"
                continue
                ;;
        esac

        if [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]]; then
            echo "ERROR: Could not resolve download URL for $ADDON_KEY"
            continue
        fi

        if [[ -n "$DOWNLOAD_URL" ]]; then
            echo "INFO: Downloading from $DOWNLOAD_URL"
            TEMP_FILE="$TMP_DIR/$ADDON_KEY.zip"
            curl -sL -o "$TEMP_FILE" "$DOWNLOAD_URL"

            if [[ ! -f "$TEMP_FILE" ]] || [[ ! -s "$TEMP_FILE" ]]; then
                echo "ERROR: Download failed for $ADDON_KEY"
                DOWNLOAD_URL=""
            fi
        fi

        # Clean existing addon directory (moz.build and jar.mn will be regenerated)
        if [[ -d "$ADDON_DIR" ]]; then
            rm -rf "$ADDON_DIR"
        fi

        if [[ -n "$DOWNLOAD_URL" ]]; then
            mkdir -p "$ADDON_DIR"
            echo "INFO: Unpacking $ADDON_KEY..."
            unzip -q -o "$TEMP_FILE" -d "$ADDON_DIR"
            flatten_single_root_if_needed "$ADDON_DIR"
        else
            echo "WARNING: Creating stub addon for $ADDON_KEY because download was not available"
            create_stub_manifest "$ADDON_DIR" "$ADDON_KEY" "$ADDON_ID"
        fi
    fi

    # Always regenerate moz.build by scanning actual files in the addon directory.
    # This ensures hashed filenames (e.g. Vite output) are always up to date.
    echo "INFO: Generating moz.build for $ADDON_KEY (scanning actual files)"
    {
        echo 'DEFINES["MOZ_APP_VERSION"] = CONFIG["MOZ_APP_VERSION"]'
        echo 'DEFINES["MOZ_APP_MAXVERSION"] = CONFIG["MOZ_APP_MAXVERSION"]'
        echo ''
        echo 'JAR_MANIFESTS += ["jar.mn"]'
        echo ''

        # Add root-level files as FINAL_TARGET_FILES (exclude build system files)
        while IFS= read -r -d '' file; do
            BASENAME=$(basename "$file")
            echo "FINAL_TARGET_FILES.features[\"$ADDON_ID\"] += [\"$BASENAME\"]"
        done < <(find "$ADDON_DIR" -maxdepth 1 -type f ! -name "moz.build" ! -name "jar.mn" -print0 | sort -z)

        # Add files in subdirectories as FINAL_TARGET_FILES with subdir keys
        while IFS= read -r -d '' dir; do
            DIRNAME=$(basename "$dir")
            echo ''
            # Check for nested subdirectories (e.g. _locales/en/)
            while IFS= read -r -d '' subfile; do
                RELPATH="${subfile#"$ADDON_DIR/"}"
                # Split path into components for nested FINAL_TARGET_FILES keys
                PARTS=(${RELPATH//\// })
                if [[ ${#PARTS[@]} -eq 2 ]]; then
                    echo "FINAL_TARGET_FILES.features[\"$ADDON_ID\"][\"$DIRNAME\"] += [\"$RELPATH\"]"
                elif [[ ${#PARTS[@]} -eq 3 ]]; then
                    echo "FINAL_TARGET_FILES.features[\"$ADDON_ID\"][\"${PARTS[0]}\"][\"${PARTS[1]}\"] += [\"$RELPATH\"]"
                elif [[ ${#PARTS[@]} -ge 4 ]]; then
                    # For deeply nested files, use up to 3 levels of keys
                    echo "FINAL_TARGET_FILES.features[\"$ADDON_ID\"][\"${PARTS[0]}\"][\"${PARTS[1]}\"] += [\"$RELPATH\"]"
                fi
            done < <(find "$dir" -type f -print0 | sort -z)
        done < <(find "$ADDON_DIR" -maxdepth 1 -type d ! -path "$ADDON_DIR" -print0 | sort -z)

    } > "$ADDON_DIR/moz.build"

    # Also sync to src/ directory for source tracking
    SRC_ADDON_DIR="$PROJECT_DIR/src/browser/extensions/$ADDON_KEY"
    mkdir -p "$SRC_ADDON_DIR"
    sync_file_to_src "$ADDON_DIR/moz.build" "$SRC_ADDON_DIR/moz.build"
    echo "INFO: Synced moz.build to src/browser/extensions/$ADDON_KEY/"

    # Always regenerate jar.mn by scanning actual directory structure
    echo "INFO: Generating jar.mn for $ADDON_KEY (scanning actual files)"
    {
        echo "browser.jar:"

        if [[ -f "$ADDON_DIR/manifest.json" ]]; then
            echo "    builtin-addons/$ADDON_KEY/manifest.json (manifest.json)"
        fi

        # Add root-level files (excluding manifest.json, moz.build, jar.mn)
        while IFS= read -r -d '' file; do
            BASENAME=$(basename "$file")
            if [[ "$BASENAME" != "manifest.json" && "$BASENAME" != "moz.build" && "$BASENAME" != "jar.mn" ]]; then
                echo "    builtin-addons/$ADDON_KEY/$BASENAME ($BASENAME)"
            fi
        done < <(find "$ADDON_DIR" -maxdepth 1 -type f -print0 | sort -z)

        # Add directories with glob patterns
        while IFS= read -r -d '' dir; do
            DIRNAME=$(basename "$dir")
            # Use ** glob for directories that may have subdirs (like _locales)
            if find "$dir" -mindepth 2 -type f -print -quit 2>/dev/null | grep -q .; then
                echo "    builtin-addons/$ADDON_KEY/$DIRNAME/ ($DIRNAME/**/*)"
            else
                echo "    builtin-addons/$ADDON_KEY/$DIRNAME/ ($DIRNAME/*)"
            fi
        done < <(find "$ADDON_DIR" -maxdepth 1 -type d ! -path "$ADDON_DIR" -print0 | sort -z)

    } > "$ADDON_DIR/jar.mn"

    # Sync jar.mn to src/ too
    sync_file_to_src "$ADDON_DIR/jar.mn" "$SRC_ADDON_DIR/jar.mn"

    # Verify manifest.json exists and has required gecko ID
    if [[ ! -f "$ADDON_DIR/manifest.json" ]]; then
        echo "WARNING: $ADDON_KEY has no manifest.json after extraction. Creating stub manifest."
        create_stub_manifest "$ADDON_DIR" "$ADDON_KEY" "$ADDON_ID"

        # Regenerate descriptors so FINAL_TARGET_FILES and jar.mn are consistent.
        {
            echo 'DEFINES["MOZ_APP_VERSION"] = CONFIG["MOZ_APP_VERSION"]'
            echo 'DEFINES["MOZ_APP_MAXVERSION"] = CONFIG["MOZ_APP_MAXVERSION"]'
            echo ''
            echo 'JAR_MANIFESTS += ["jar.mn"]'
            echo ''
            echo "FINAL_TARGET_FILES.features[\"$ADDON_ID\"] += [\"manifest.json\"]"
        } > "$ADDON_DIR/moz.build"

        {
            echo "browser.jar:"
            echo "    builtin-addons/$ADDON_KEY/manifest.json (manifest.json)"
        } > "$ADDON_DIR/jar.mn"

        sync_file_to_src "$ADDON_DIR/moz.build" "$SRC_ADDON_DIR/moz.build"
        sync_file_to_src "$ADDON_DIR/jar.mn" "$SRC_ADDON_DIR/jar.mn"
    fi

    GECKO_ID=$(jq -r '.browser_specific_settings.gecko.id // empty' "$ADDON_DIR/manifest.json" 2>/dev/null)
    if [[ -z "$GECKO_ID" ]]; then
        echo "WARNING: $ADDON_KEY manifest.json has no browser_specific_settings.gecko.id"
        echo "WARNING: The extension may not load correctly as a builtin addon"
    else
        echo "INFO: $ADDON_KEY gecko ID: $GECKO_ID"
    fi

    PROCESSED_ADDONS+=("$ADDON_KEY")
    echo "OK: $ADDON_KEY is ready"
done

# Register addons in moz.build if not already present
MOZBUILD_FILE="$EXTENSIONS_DIR/moz.build"
if [[ -f "$MOZBUILD_FILE" ]]; then
    CHANGED=false
    for ADDON in "${PROCESSED_ADDONS[@]}"; do
        if ! grep -q "\"$ADDON\"" "$MOZBUILD_FILE"; then
            echo ""
            echo "INFO: Adding '$ADDON' to $MOZBUILD_FILE DIRS"
            # Insert before the closing bracket of DIRS
            sed -i "/^]/i\\    \"$ADDON\"," "$MOZBUILD_FILE"
            CHANGED=true
        fi
    done

    if [[ "$CHANGED" == "true" ]]; then
        echo "INFO: Updated $MOZBUILD_FILE"
    else
        echo "INFO: All addons already registered in moz.build"
    fi
fi

# Cleanup temp dir
rm -rf "$TMP_DIR"

echo ""
echo "=== Addon integration complete ==="
echo "Processed addons: ${PROCESSED_ADDONS[*]}"
echo ""
echo "Next steps:"
echo "  1. Build: npm run build"
echo "  2. Run: npm run browser"
